Search.appendIndex(
    [
                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument",
            "name": "Argument",
            "summary": "Argument",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020hook\u0020argument.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aget_php_parser_argument\u0028\u0029",
            "name": "get_php_parser_argument",
            "summary": "Get\u0020PHP\u0020Parser\u0020argument\u0020object.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_get_php_parser_argument"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "Get\u0020name.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_get_name"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aget_param_tag\u0028\u0029",
            "name": "get_param_tag",
            "summary": "Get\u0020param\u0020tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_get_param_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aset_param_tag\u0028\u0029",
            "name": "set_param_tag",
            "summary": "Set\u0020param\u0020tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_set_param_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aget_type\u0028\u0029",
            "name": "get_type",
            "summary": "Get\u0020type,",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_get_type"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003Aget_description\u0028\u0029",
            "name": "get_description",
            "summary": "Get\u0020description.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#method_get_description"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003A\u0024arg",
            "name": "arg",
            "summary": "PHP\u0020Parser\u0020argument\u0020object.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#property_arg"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Argument\u003A\u003A\u0024param_tag",
            "name": "param_tag",
            "summary": "Parameter\u0020tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Argument.html#property_param_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog",
            "name": "Changelog",
            "summary": "Changelog",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020changelog.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003Aget_first\u0028\u0029",
            "name": "get_first",
            "summary": "Get\u0020first\u0020version.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#method_get_first"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003Aadd_item\u0028\u0029",
            "name": "add_item",
            "summary": "Add\u0020item.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#method_add_item"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Count.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#method_count"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Get\u0020iterator.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#method_getIterator"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Changelog\u003A\u003A\u0024items",
            "name": "items",
            "summary": "Items.",
            "url": "classes/Pronamic-WordPress-Documentor-Changelog.html#property_items"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\ChangelogFactory",
            "name": "ChangelogFactory",
            "summary": "Changelog\u0020Factory",
            "url": "classes/Pronamic-WordPress-Documentor-ChangelogFactory.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\ChangelogFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020changelog\u0020from\u0020doc\u0020block.",
            "url": "classes/Pronamic-WordPress-Documentor-ChangelogFactory.html#method_create"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\DefaultPrinter",
            "name": "DefaultPrinter",
            "summary": "Default\u0020Printer",
            "url": "classes/Pronamic-WordPress-Documentor-DefaultPrinter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\DefaultPrinter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constrcuct\u0020default\u0020printer.",
            "url": "classes/Pronamic-WordPress-Documentor-DefaultPrinter.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\DefaultPrinter\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render.",
            "url": "classes/Pronamic-WordPress-Documentor-DefaultPrinter.html#method_render"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor",
            "name": "Documentor",
            "summary": "Documentor",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020documentor.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Aget_hooks\u0028\u0029",
            "name": "get_hooks",
            "summary": "Get\u0020hooks.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_get_hooks"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Aget_actions\u0028\u0029",
            "name": "get_actions",
            "summary": "Get\u0020actions.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_get_actions"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Aget_filters\u0028\u0029",
            "name": "get_filters",
            "summary": "Get\u0020filters.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_get_filters"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Arelative\u0028\u0029",
            "name": "relative",
            "summary": "Get\u0020relative\u0020path.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_relative"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Ashould_parse_tag\u0028\u0029",
            "name": "should_parse_tag",
            "summary": "Check\u0020if\u0020the\u0020specified\u0020tag\u0020name\u0020should\u0020be\u0020parsed.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_should_parse_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#method_parse"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003A\u0024hooks",
            "name": "hooks",
            "summary": "Hooks.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#property_hooks"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Documentor\u003A\u003A\u0024prefixes",
            "name": "prefixes",
            "summary": "Prefixes.",
            "url": "classes/Pronamic-WordPress-Documentor-Documentor.html#property_prefixes"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook",
            "name": "Hook",
            "summary": "Hook",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020hook.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_file\u0028\u0029",
            "name": "get_file",
            "summary": "Get\u0020file.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_file"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_call\u0028\u0029",
            "name": "get_call",
            "summary": "Get\u0020call.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_call"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_tag\u0028\u0029",
            "name": "get_tag",
            "summary": "Get\u0020tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_doc_comment\u0028\u0029",
            "name": "get_doc_comment",
            "summary": "Get\u0020doc\u0020comment.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_doc_comment"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aset_doc_comment\u0028\u0029",
            "name": "set_doc_comment",
            "summary": "Set\u0020doc\u0020comment.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_set_doc_comment"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_doc_block\u0028\u0029",
            "name": "get_doc_block",
            "summary": "Get\u0020doc\u0020block.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_doc_block"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_start_line\u0028\u0029",
            "name": "get_start_line",
            "summary": "Get\u0020start\u0020line.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_start_line"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_end_line\u0028\u0029",
            "name": "get_end_line",
            "summary": "Get\u0020end\u0020line.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_end_line"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_summary\u0028\u0029",
            "name": "get_summary",
            "summary": "Get\u0020summary.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_summary"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_description\u0028\u0029",
            "name": "get_description",
            "summary": "Get\u0020description.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_description"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Ais_filter\u0028\u0029",
            "name": "is_filter",
            "summary": "Is\u0020filter.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_is_filter"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Ais_action\u0028\u0029",
            "name": "is_action",
            "summary": "Is\u0020action.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_is_action"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Ais_deprecated\u0028\u0029",
            "name": "is_deprecated",
            "summary": "Is\u0020deprecated.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_is_deprecated"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024tag",
            "name": "tag",
            "summary": "Tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_arguments\u0028\u0029",
            "name": "get_arguments",
            "summary": "Arguments.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_arguments"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_changelog\u0028\u0029",
            "name": "get_changelog",
            "summary": "Changelog.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_changelog"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aset_changelog\u0028\u0029",
            "name": "set_changelog",
            "summary": "Set\u0020changelog.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_set_changelog"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_since\u0028\u0029",
            "name": "get_since",
            "summary": "Get\u0020since.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_since"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003Aget_since_version\u0028\u0029",
            "name": "get_since_version",
            "summary": "Get\u0020since\u0020version.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#method_get_since_version"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024file",
            "name": "file",
            "summary": "File.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_file"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024call",
            "name": "call",
            "summary": "Function\u0020call.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_call"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024doc_comment",
            "name": "doc_comment",
            "summary": "Doc\u0020comment.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_doc_comment"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024doc_block",
            "name": "doc_block",
            "summary": "Doc\u0020block.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_doc_block"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Hook\u003A\u003A\u0024changelog",
            "name": "changelog",
            "summary": "Changelog.",
            "url": "classes/Pronamic-WordPress-Documentor-Hook.html#property_changelog"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\HooksterPrinter",
            "name": "HooksterPrinter",
            "summary": "Hookster\u0020Printer",
            "url": "classes/Pronamic-WordPress-Documentor-HooksterPrinter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\HooksterPrinter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constrcuct\u0020Hookster\u0020printer.",
            "url": "classes/Pronamic-WordPress-Documentor-HooksterPrinter.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\HooksterPrinter\u003A\u003Aget_hooks\u0028\u0029",
            "name": "get_hooks",
            "summary": "Get\u0020the\u0020hooks\u0020to\u0020print.",
            "url": "classes/Pronamic-WordPress-Documentor-HooksterPrinter.html#method_get_hooks"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\HooksterPrinter\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "JSON\u0020Serialize.",
            "url": "classes/Pronamic-WordPress-Documentor-HooksterPrinter.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\HooksterPrinter\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render.",
            "url": "classes/Pronamic-WordPress-Documentor-HooksterPrinter.html#method_render"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\NamespaceResolver",
            "name": "NamespaceResolver",
            "summary": "Namespace\u0020Resolver",
            "url": "classes/Pronamic-WordPress-Documentor-NamespaceResolver.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\NamespaceResolver\u003A\u003AenterNode\u0028\u0029",
            "name": "enterNode",
            "summary": "Enter\u0020node.",
            "url": "classes/Pronamic-WordPress-Documentor-NamespaceResolver.html#method_enterNode"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\NamespaceResolver\u003A\u003A\u0024namespace",
            "name": "namespace",
            "summary": "Namespace.",
            "url": "classes/Pronamic-WordPress-Documentor-NamespaceResolver.html#property_namespace"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since",
            "name": "Since",
            "summary": "Since",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020since\u0020object.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003Aget_version\u0028\u0029",
            "name": "get_version",
            "summary": "Get\u0020version.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#method_get_version"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003Aget_description\u0028\u0029",
            "name": "get_description",
            "summary": "Get\u0020description.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#method_get_description"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003Aget_tag\u0028\u0029",
            "name": "get_tag",
            "summary": "Get\u0020tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#method_get_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003A\u0024version",
            "name": "version",
            "summary": "Version.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#property_version"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Description.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#property_description"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Since\u003A\u003A\u0024tag",
            "name": "tag",
            "summary": "Tag.",
            "url": "classes/Pronamic-WordPress-Documentor-Since.html#property_tag"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Tag",
            "name": "Tag",
            "summary": "Tag",
            "url": "classes/Pronamic-WordPress-Documentor-Tag.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Tag\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020hook.",
            "url": "classes/Pronamic-WordPress-Documentor-Tag.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Tag\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "Get\u0020name.",
            "url": "classes/Pronamic-WordPress-Documentor-Tag.html#method_get_name"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Tag\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Name.",
            "url": "classes/Pronamic-WordPress-Documentor-Tag.html#property_name"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\Tag\u003A\u003A\u0024arg",
            "name": "arg",
            "summary": "Argument.",
            "url": "classes/Pronamic-WordPress-Documentor-Tag.html#property_arg"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\TagPrinter",
            "name": "TagPrinter",
            "summary": "Tag\u0020Printer",
            "url": "classes/Pronamic-WordPress-Documentor-TagPrinter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\TagPrinter\u003A\u003Aprint\u0028\u0029",
            "name": "print",
            "summary": "Print\u0020PHP\u0020Parser\u0020epxression.",
            "url": "classes/Pronamic-WordPress-Documentor-TagPrinter.html#method_print"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\TemplatePrinter",
            "name": "TemplatePrinter",
            "summary": "Template\u0020Printer",
            "url": "classes/Pronamic-WordPress-Documentor-TemplatePrinter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\TemplatePrinter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constrcuct\u0020default\u0020printer.",
            "url": "classes/Pronamic-WordPress-Documentor-TemplatePrinter.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor\\TemplatePrinter\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render.",
            "url": "classes/Pronamic-WordPress-Documentor-TemplatePrinter.html#method_render"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Documentor",
            "name": "Documentor",
            "summary": "",
            "url": "namespaces/pronamic-wordpress-documentor.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress",
            "name": "WordPress",
            "summary": "",
            "url": "namespaces/pronamic-wordpress.html"
        },                {
            "fqsen": "\\Pronamic",
            "name": "Pronamic",
            "summary": "",
            "url": "namespaces/pronamic.html"
        }            ]
);
